### ISSUE TITLE
Default todo location not registering

### ISSUE THREAD

**Issue by proehlen** [zombieleet/duty#4]
After installing I ran duty and duty add with the following results.  It doesn't seem to register that I've got a .duty.json file.
```
[peter@peter-mba ~]$ duty
default todo location not found, use "/home/peter/.duty.json" as default (y/n) y
```
Confirm file exists:
```
[peter@peter-mba ~]$ ls -al .duty.json 
-rw-r--r-- 1 peter peter 2 Jul 23 00:57 .duty.json
```

Attempt to add a task:
```
[peter@peter-mba ~]$ duty add "test"
default todo location not found, use "/home/peter/.duty.json" as default (y/n) /usr/lib/node_modules/duty-js/src/utils.js:49
  return ff.add({todo, category, hash}, manager)
            ^

TypeError: ff.add is not a function
    at addOption (/usr/lib/node_modules/duty-js/src/utils.js:49:13)
    at Command.commander.version.command.description.action (/usr/lib/node_modules/duty-js/cli.js:32:12)
    at Command.listener (/usr/lib/node_modules/duty-js/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/usr/lib/node_modules/duty-js/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/lib/node_modules/duty-js/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/usr/lib/node_modules/duty-js/cli.js:177:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
[peter@peter-mba ~]$ 
```

**Comment by proehlen** [comment]
I'm running Manjaro linux and I had to install duty globally using sudo in case it's relevant.

**Comment by zombieleet** [comment]
@proehlen can you kindly check your verison of node.js with node --version

**Comment by proehlen** [comment]
@zombieleet  I'm running v8.1.3

**Comment by zombieleet** [comment]
did you try running duty with sudo ?

**Comment by zombieleet** [comment]
I just updated nodeJs and got the same error. I will be fixing the bug few minuets from now

**Comment by zombieleet** [comment]
did you try running duty with sudo ?

**Comment by proehlen** [comment]
Hi, `/usr/lib/node_modules/duty-js/config.json` contains:
```
{"location":"/root/.duty.json","notification":"yes","timeout":60000}
```
I have to install with sudo to get it to install globally but I don't want to run it as sudo.  So I think that's the issue.  Thanks for your time.

**Comment by zombieleet** [comment]
if you don't want to run it with sudo, you can rename `"/root/.duty.json"` to `"/home/peter/.duty.json"`

**Comment by zombieleet** [comment]
The bug is as a result of the mode of "config.json".

**Comment by zombieleet** [comment]
install the new update, and see if it fixes your issue. Thanks for detecting this bug

**Comment by proehlen** [comment]
New error now:
```
[peter@peter-mba ~]$ sudo npm install -g duty-js
[sudo] password for peter: 
/usr/bin/duty -> /usr/lib/node_modules/duty-js/cli.js
/usr/lib
└─┬ duty-js@3.0.5 
  ├── colors@1.1.2 
  ├── commander@2.11.0 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── moment@2.18.1 
  └─┬ node-notifier@5.1.2 
    ├── growly@1.3.0 
    ├── semver@5.3.0 
    ├── shellwords@0.1.0 
    └─┬ which@1.2.14 
      └── isexe@2.0.0 

[peter@peter-mba ~]$ duty
default todo location not found, use "/home/peter/.duty.json" as default (y/n) y
{ Error: EACCES: permission denied, open '/usr/lib/node_modules/duty-js/config.json'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at _f (/usr/lib/node_modules/duty-js/index.js:63:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/node_modules/duty-js/config.json' }
```

**Comment by zombieleet** [comment]
wrong permission, i pushed the wrong code. another patch have been released. If the error persists, you have to change the mode of `/usr/lib/node_modules/duty-js/config.json` to 777

**Comment by proehlen** [comment]
Ok, I scrubbed all of the existing files from my system and reinstalled with @latest and I still had to change the mode of that file to 777 manually. But it's all working now, cheers.
